### ISSUE TITLE
Unable to enter minutes > 10 when typing numbers

### ISSUE THREAD

**Issue by kevinansfield** [minutebase/ember-time-field#1]
Steps to reproduce on http://minutebase.github.io/ember-time-field/:
1. Click the minutes field
2. Type `40`
3. Minutes field shows `00`

Expected result: Minutes field shows `40`.

Browser: Safari 9.0.1 on OS X 10.11.1 Beta.

**Comment by rlivsey** [comment]
Overzealous copy & paste between the hours & minutes handling!

Should work as expected now.

Thanks
